import { Amplify } from 'aws-amplify';

/**
 * Cognito Configuration Interface
 * Matches the structure created by the Lambda deployment function
 */
interface CognitoConfig {
  region: string;
  userPoolId: string;
  userPoolClientId: string;
  hostedUIDomain: string;
  authenticationFlowType: string;
  oauth: {
    domain: string;
    scope: string[];
    redirectSignIn: string;
    redirectSignOut: string;
    responseType: string;
  };
  groups: {
    users: string;
    admins: string;
  };
  routes: {
    user: string;
    admin: string;
  };
}

/**
 * Configure AWS Amplify with Cognito authentication settings.
 * 
 * This function fetches the Cognito configuration from the deployed
 * cognito-config.json file (generated by the Lambda function during
 * Amplify app deployment) and configures Amplify Auth accordingly.
 * 
 * The configuration file is automatically created and updated by the
 * backend Lambda with the correct User Pool IDs, callback URLs, and
 * OAuth settings.
 * 
 * @returns Promise<CognitoConfig> The loaded Cognito configuration
 * @throws Error if configuration cannot be loaded or is invalid
 */
export async function configureAmplify(): Promise<CognitoConfig> {
  try {
    console.log('Loading Cognito configuration...');
    
    // Fetch Cognito config from public path
    // This file is created by the Lambda deployment function
    const response = await fetch('/cognito-config.json');
    
    if (!response.ok) {
      throw new Error(`Failed to fetch cognito-config.json: ${response.status} ${response.statusText}`);
    }
    
    const cognitoConfig: CognitoConfig = await response.json();
    
    // Validate required fields
    if (!cognitoConfig.userPoolId || !cognitoConfig.userPoolClientId) {
      throw new Error('Invalid Cognito configuration: missing required fields');
    }
    
    console.log('Cognito configuration loaded successfully');
    console.log('User Pool ID:', cognitoConfig.userPoolId);
    console.log('Region:', cognitoConfig.region);
    
    // Configure Amplify with Cognito settings
    Amplify.configure({
      Auth: {
        Cognito: {
          // User Pool configuration
          userPoolId: cognitoConfig.userPoolId,
          userPoolClientId: cognitoConfig.userPoolClientId,
          
          // OAuth configuration for Hosted UI
          loginWith: {
            oauth: {
              domain: cognitoConfig.oauth.domain,
              scopes: cognitoConfig.oauth.scope,
              redirectSignIn: [cognitoConfig.oauth.redirectSignIn],
              redirectSignOut: [cognitoConfig.oauth.redirectSignOut],
              responseType: cognitoConfig.oauth.responseType as 'code' | 'token',
            },
          },
        },
      },
    });
    
    console.log('Amplify configured successfully');
    
    return cognitoConfig;
    
  } catch (error) {
    console.error('Failed to configure Amplify:', error);
    
    // Provide helpful error messages for common issues
    if (error instanceof TypeError && error.message.includes('fetch')) {
      throw new Error(
        'Unable to load authentication configuration. Please ensure the app is deployed correctly.'
      );
    }
    
    throw error;
  }
}

/**
 * Get the current Cognito configuration without reconfiguring Amplify.
 * Useful for accessing group names, routes, and other metadata.
 * 
 * @returns Promise<CognitoConfig> The current Cognito configuration
 * @throws Error if configuration cannot be loaded
 */
export async function getCognitoConfig(): Promise<CognitoConfig> {
  try {
    const response = await fetch('/cognito-config.json');
    
    if (!response.ok) {
      throw new Error(`Failed to fetch cognito-config.json: ${response.status}`);
    }
    
    return await response.json();
    
  } catch (error) {
    console.error('Failed to get Cognito configuration:', error);
    throw error;
  }
}

/**
 * Check if Amplify is configured with valid Cognito settings.
 * 
 * @returns boolean True if Amplify appears to be configured
 */
export function isAmplifyConfigured(): boolean {
  try {
    // Attempt to get current config
    const config = Amplify.getConfig();
    return !!(config.Auth?.Cognito?.userPoolId);
  } catch {
    return false;
  }
}